CREATE TABLE CITY (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    city_name VARCHAR2(100) NOT NULL
);

INSERT INTO CITY (id, city_name) VALUES (1, 'Bengaluru');
INSERT INTO CITY (id, city_name) VALUES (2, 'Hyderabad');
INSERT INTO CITY (id, city_name) VALUES (3, 'Chennai');

CREATE TABLE LANGUAGE (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    city_id NUMBER,
    language_name VARCHAR2(100) NOT NULL
);
INSERT INTO LANGUAGE (id, city_id, language_name) VALUES (1, 1, 'Kannada');
INSERT INTO LANGUAGE (id, city_id, language_name) VALUES (2, 1, 'Telugu');
INSERT INTO LANGUAGE (id, city_id, language_name) VALUES (3, 1, 'Tamil');
INSERT INTO LANGUAGE (id, city_id, language_name) VALUES (4, 1, 'Hindi');

INSERT INTO LANGUAGE (id, city_id, language_name) VALUES (5, 2, 'Kannada');
INSERT INTO LANGUAGE (id, city_id, language_name) VALUES (6, 2, 'Telugu');
INSERT INTO LANGUAGE (id, city_id, language_name) VALUES (7, 2, 'Tamil');

INSERT INTO LANGUAGE (id, city_id, language_name) VALUES (8, 3, 'Tamil');



